- src/App.jsx
> App.jsx의 기본 리액트 설치시 코드 제거 후 rafce 명령어 적용하여 깔끔하게 바꿔봤습니다!
> 
> 이거 올리면서 생각난건데, 풀리퀘 쓰다가 npm install 안한거 생각나서 이거 쓰면서 지금했습니다..npm run 잘 되구요 크게 문제없을것 같네요!
> test-commit!!!!

- src/assets/xbox.svg
- src/components/popup/PagefilterPopup/PagefilterPopup.jsx
- src/components/popup/PagefilterPopup/PagefilterPopup.styles.jsx
- src/components/popup/recordPopup/RecordPopup.jsx
- src/components/popup/recordPopup/RecordPopup.styles.jsx
> 방만들기 팝업 컴포넌트 생성 완료

- src/components/InfoBody/ButtonGroup2.jsx
- src/components/InfoBody/InfoBody.jsx
- src/components/InfoBody/InfoBody.styles.jsx
- src/components/Member/MemberHeader.jsx
> [Feat] 즐겨찾기 팝업 구현

- build.sh
> 배포를 위한 build.sh 파일 생성
> 배포를 미리 해놓아야 담주에 팀원들한테도 보여줄 수 있고 배포할때 나는 버그도 빠르게 줄일 수 있을 거같아서 미리 생성하였습니다-!
> [Feat] 빌드 스크립트 작성

- .github/workflows/main.yml
> 이전에 냈던 pr이랑 같은 내용으로 배포를 위한 github actions 작성하였습니다-!
> 배포하는 과정은 너무 간단해서 제가 그냥 바로 끝냈는데 배포 어떻게 했는지 궁금하신 분들은 (https://velog.io/@049494/Vercel%EB%A1%9C-%ED%8C%80-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%AC%B4%EB%A3%8C-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0)
이거 참고해보면 좋을거같아요-!
> [Feat] 배포를 위한 workflow 작성

- src/apis/getRoomInfo.js
- src/components/InfoBody/TapGroup2.jsx
- src/components/InfoBody/TapGroup2.styles.jsx
- src/routers/Router.jsx
- vite.config.js
1. 프록시 추가로 CORS 에러 해결했습니다.
실제 배포에서는 vercecl에서 vercel.json 해서 설정파일만 추가로 올리면 가능하다고 합니다.
2. 책목록 선택 시 방 상세정보 api 연동 코드 저장했습니다.
>
> Feat : vite.config 파일 수정 (프록시 추가), 책 목록 선택시 방 상세정보 API 연동 완료

- src/apis/getRoomInfo.js
- src/apis/instance/index.js
제가 작성한 코드 참고해서 앞으로 api 호출하는 코드에 index파일 import 해서 쓰시면 될 것 같습니다.
>
> Fix : axios instance 파일 추가

- package-lock.json
- src/apis/authApi.js
- src/apis/instance/apiClient.js
- src/components/userInputField/UserInputField.jsx
- src/pages/home/Home.jsx
- src/pages/login/Login.jsx
> 로그인 Api 개발 완료 하였습니다. 이제 백엔드에서 회원가입 처리해둔 유저 정보(이메일, 비번) 이용해서 로그인 하시면 로그인 가능합니다. 추가적으로, accessToken 헤더에 추가하고, refreshToken은 유저가 로컬에서 저장하고있는지까지 확인 되었습니다.
참고로 현재 로그인 완료후 Home.jsx에서 몇가지 axios 에러또는 Http 메서드 오류가 뜨는데, 이건 재가 액세스 토큰 재발급 로직 검증을 위해서 임의로 더미 요청을 보내둔거라 뜨는 오류이니 크게 신경안쓰셔도됩니다.
> [Feat] 로그인 api, accessToken 재발급 api 구현완료

- src/apis/authApi.js
- src/apis/instance/apiClient.js
- src/apis/profileApi.js
- src/components/bookFrame/BookFrame.jsx
- src/pages/category/Category.jsx
- src/pages/category/Category.styles.jsx
- src/pages/home/Home.jsx
- src/pages/home/Home.styles.jsx
- src/pages/home/blue.svg
- src/pages/home/gray.svg
- src/pages/profile/Profile.jsx
- src/pages/profile/Profile.styles.jsx
> 홈화면 닉네임연동, 베스트셀러 연동
> 현재 프로필 사진 업로드 api 개발 중에 순서가 꼬여서 홈화면 먼저 개발하고 올리는 바람에 프로필 api는 미완성인 상태에서 올렸습니다. 다음 pr 때는 프로필 업로드 완성해서 다시 pr 올리겠습니다.! 일단 현재 pr 만 머지한 상태에서는 프로필 업로드 부분은 정상 작동 안합니다!
> [Feat] 홈화면 닉네임연동, 베스트셀러 연동

- src/apis/popularApi.js
- src/pages/home/Home.jsx
- src/pages/home/Home.styles.jsx
> [Feat]읽기횟수 많은 책 api 구현

- src/apis/bookmarkAPI.js
- src/apis/mypageAPI.js
- src/apis/mypageReadingCalendarAPI.js
- src/pages/mypage/Mypage.styles.jsx
- src/pages/mypage/mypage.jsx
- src/pages/mypage/readingcalendar/CalendarContent.jsx
> closed #45 
> 마이페이지 첫화면 회원정보 불러오기
> 독서달력 오류 수정
> 즐겨찾기 오류 수정
> 책제목이 너무 길어서 깨지는 부분은 나중에 수정할게요-!
> [Feat] 마이페이지 마무리

- src/apis/bookmarkAPI.js
- src/apis/mypageAPI.js
- src/apis/mypageReadingCalendarAPI.js
- src/apis/searchAPI.js
- src/pages/mypage/Mypage.styles.jsx
- src/pages/mypage/mypage.jsx
- src/pages/mypage/readingcalendar/CalendarContent.jsx
- src/pages/search/BookItem.jsx
- src/pages/search/CountSlider.jsx
- src/pages/search/FilterPopup.jsx
- src/pages/search/RoomItem.jsx
- src/pages/search/SearchResults.jsx
- src/pages/search/search.jsx
>  #41 
> Search page 필터설정 수정 & 책이랑 방 경로 설정
이전에 설정한 필터 적용되어 있음
> [Feat] Search page 필터설정 수정 & 책이랑 방 경로 설정

- src/apis/deleteRecordApi.js
- src/apis/progressApi.js
- src/components/bookFrame/BookFrame.jsx
- src/components/bookFrame/BookFrame.styles.jsx
- src/pages/home/Home.jsx
- src/pages/record/Book.jsx
- src/pages/record/Book.styles.jsx
- src/pages/record/Record.jsx
> 진행중 기록 "->" 클릭 시 라우팅되는 상세페이지 연동완료
> 더보기 팝업 삭제 버튼 동작 구현
> 더보기 팝업 상세보기 버튼 동작 구현
> 책표지 클릭시 ReadWith 페이지로 라우팅
> [Feat] 진행 중 기록 조회 및 삭제 api 연동 

- src/apis/recruitRoomApi.js
- src/pages/home/Home.jsx
- src/pages/home/Room.jsx
- src/pages/home/Room.styles.jsx
> 모집중인 방 api 구현 완료하였습니다.
> 클릭시 rooms/:roomId 로 라우팅 됩니다.
> [Feat] 모집 방 api 구현

- package-lock.json
- package.json
- src/pages/home/Home.jsx
- src/pages/home/Home.styles.jsx
- src/pages/record/Record.jsx
- 불필요한 주석코드 삭제
- 베셀 이미지 클릭시 isbn 페이지 이동
- 베셀 캐러셀 라이브러리 적용
- css 일부 수정
>
> [Fix]  홈화면 수정사항 종합 수정

- src/components/bookFrame/BookFrame.jsx
- src/components/bookFrame/BookFrame.styles.jsx
- src/pages/bookmark/Bookmark.jsx
- src/pages/home/Home.styles.jsx
- src/pages/home/Room.styles.jsx
- src/pages/login/Login.jsx
- src/pages/login/Login.styles.jsx
- src/pages/record/Book.styles.jsx
- src/pages/record/Record.jsx
- src/pages/record/Record.styles.jsx
- src/pages/signup/Signup.jsx
> [Fix] css 1차 수정

- vercel.json
> [Feat] backend server 경로 수정

- src/apis/instance/apiClient.js
- src/apis/logoutApi.js
- src/pages/bookmark/Bookmark.jsx
- src/pages/collector/Collector.jsx
- src/pages/mypage/logout/LogoutPopup.jsx
- src/pages/mypage/mypage.jsx
- src/pages/mypage/readingcalendar/ReadingCalendar.jsx
- src/pages/readingLog/ReadingLog.jsx
- src/pages/record/Record.jsx
-로그아웃 api 구현
- 로그아웃 이후 라우팅 주소로 비정상 접근시 accessToken 없는 거 확인 후 접속 차단 및 login 페이지로 이동
>
> [Feat] 로그아웃 구현

- src/apis/progressApi.js
- src/pages/record/Record.jsx
> [Fix] 진행중기록 진행도순 구현

- src/components/userInputField/UserInputField.styles.jsx
- src/pages/login/Login.jsx
- src/pages/login/Login.styles.jsx
- src/pages/record/Record.styles.jsx
- src/pages/signup/Signup.jsx
- src/pages/signup/Signup.styles.jsx
> [Fix] pw 양식 및 눈 아이콘 수정

- src/pages/home/Home.jsx
- src/pages/home/Home.styles.jsx
> [Fix] 홈 스크롤 수정

- src/components/bookFrame/BookFrame.jsx
- src/components/bookFrame/BookFrame.styles.jsx
- src/pages/bookmark/Box.styles.jsx
- src/pages/home/Home.jsx
- src/pages/record/Record.jsx
- src/pages/record/Record.styles.jsx
- src/pages/signup/PasswordInput.styles.jsx
1.홈화면 진행중인 기록 ->진행중 기록 
2.더보기 눌렀을때 해당 책 테두리(hover 했던거와 똑같이)  
3.진행중 기록-> 더보기 -> 닉네임 빼기 
4."진행중 기록" 텍스트 가운데 정렬 
>
> [Fix] css 전체 수정

- src/apis/getCollectorInfo.js
- src/assets/titles/titleImages.js
- src/components/InfoBody/InfoBody.styles.jsx
- src/components/Reply/Reply.styles.jsx
- src/components/RoomBody/EntireRecord.jsx
- src/components/RoomBody/PageRecord.jsx
- src/components/RoomBody/RoomBody.jsx
- src/components/RoomHeader/RoomHeader.jsx
- src/pages/ReadWith/ReadWith.jsx
- src/pages/Test.jsx
- src/pages/collector/Collector.jsx
- src/pages/collector/Collector.styles.jsx
- src/pages/collector/CollectorPopup.jsx
- src/pages/collector/LoadingSpinner.jsx
- src/pages/mypage/Mypage.styles.jsx
> [Feat] 마이페이지 - 책산책 수집가 페이지 구현 완료

- src/components/bookFrame/BookFrame.jsx
- src/components/bookFrame/BookFrame.styles.jsx
- src/components/infoPopup/InfoPopup.jsx
- src/components/infoPopup/InfoPopup.styles.jsx
- src/pages/bookmark/Bookmark.jsx
- src/pages/bookmark/Bookmark.styles.jsx
- src/pages/bookmark/Box.styles.jsx
- src/pages/home/Home.jsx
- src/pages/home/Home.styles.jsx
- src/pages/record/Book.jsx
- src/pages/record/Record.styles.jsx
- 즐겨찾기 전체 권수 추가
- 즐겨찾기 팝업 텍스트 가운데 정렬
- 팝업화면 디자인변경 -> 토스트 팝업
- 유저진행도 소수점 버림 처리 수정
- 홈화면 진행중인 기록 책 프레임 정렬간격 css 수정
> [Fix] 전체 css수정 및 팝업화면 수정

- src/apis/authApi.js
- src/pages/bookmark/Bookmark.styles.jsx
- src/pages/bookmark/Box.jsx
- src/pages/bookmark/Box.styles.jsx
- src/pages/category/Category.styles.jsx
- src/pages/home/Home.jsx
- src/pages/home/Home.styles.jsx
- src/pages/home/Room.jsx
- src/pages/home/Room.styles.jsx
- src/pages/home/bell.svg
- src/pages/mypage/logout/LogoutPopup.jsx
- src/pages/onboarding/Onboarding.jsx
- src/pages/onboarding/Onboarding.styles.jsx
- src/pages/profile/Profile.jsx
- src/pages/profile/Profile.styles.jsx
- src/pages/record/Record.jsx
- src/pages/record/Record.styles.jsx
- src/pages/signup/PasswordInput.jsx
- src/pages/signup/PasswordInput.styles.jsx
- src/pages/signup/Signup.jsx
- src/pages/signup/Signup.styles.jsx
- src/pages/signup/ValidTestInput.styles.jsx
- 비밀번호 눈아이콘 및 기능
- 각종 Input 란 글자 넘어가는 거 수정
- 회원가입 인증과정 (이메일인증, 비밀번호 정규식)에러 메시지 스타일 수정
- 즐겨찾기 책 제목,작가 수직정렬
- 홈화면 로그아웃 버튼 구현
- 즐겨찾기 삭제 팝업 가운데 정렬
- 온보딩화면 프로필, 닉네임 연동
> [Fix] qa 내용 반영 전체 수정

- src/pages/signup/Signup.jsx
> 정규표현식으로 이메일 형식검증 추가. 형식에 어긋날시 인증메일 보내지않고 에러메시지 출력합니다
> [fix] 이메일 형식검증

- src/App.jsx
- src/components/InfoBody/ButtonGroup2.jsx
- src/components/InfoBody/InfoBody.styles.jsx
- src/components/InfoBody/TapGroup2.jsx
- src/components/commons/Footer/Footer.jsx
- src/components/commons/Footer/Footer.styles.jsx
- src/components/popup/roomPasswordPopup/RoomPasswordPopup.jsx
- src/components/popup/roomPasswordPopup/RoomPasswordPopup.styles.jsx
> [Fix] 오타 수정 및 비밀번호 글자 삭제 기능 추가

- src/apis/bookmarkAPI.js
- src/pages/bookmark/Bookmark.jsx
- src/pages/bookmark/Box.jsx
- src/pages/bookmark/Box.styles.jsx
> 즐겨찾기 화면에서 책 컴포넌트(영역 어디든) 클릭시 해당책 isbn페이지로 이동
> [fix] 즐겨찾기 클릭시 isbn페이지로 이동

- src/pages/readingLog/ReadingLog.jsx
- src/pages/readingLog/ReadingLog.styles.jsx
- src/pages/search/search.jsx
> 책목록, 같이읽기목록 API parameter 잘못 전달 오류 수정
>
> [Fix] listType, searchType params missing

- src/apis/authApi.js
- src/apis/instance/apiClient.js
- src/components/infoPopup/InfoPopup.jsx
> 액세스 토큰 재발급 코드 수정해봤는데 테스트 부탁드립니다!
> [fix] 액세스토큰 재발급 수정

- src/pages/category/Category.styles.jsx
- src/pages/home/Home.styles.jsx
- src/pages/login/Login.styles.jsx
- src/pages/mypage/accountInfo/Account.styles.jsx
- src/pages/onboarding/Onboarding.styles.jsx
- src/pages/profile/Profile.styles.jsx
- src/pages/signup/Signup.styles.jsx
- /login
- /signUp
- /profile
- category
- onboarding
- home
이렇게 제가 디자인한 페이지 높이 모두 100vh 로 수정했습니다
>
> [fix] 높이 100vh 수정

- src/apis/postEnter.js
- src/components/InfoBody/ButtonGroup2.jsx
- src/components/InfoBody/InfoBody.styles.jsx
- src/components/MakeReadwithTogether/DatePicker.jsx
- src/components/MakeReadwithTogether/MakeReadwithTogether.jsx
- src/components/RWFooter/RWFooter.styles.jsx
- src/components/commons/Footer/Footer.jsx
- src/components/popup/recordPopup/RecordPopup.jsx
- src/components/popup/roomPasswordPopup/RoomPasswordPopup.jsx
- src/pages/Preview/PreviewBody.jsx
- src/pages/record/Record.styles.jsx
> [Fix] css 수정

- src/apis/searchAPI.js
- src/pages/search/search.jsx
> 책 조회API 임계값 수정
> 감색 필터 localstorage에 저장
> 리뷰 후 머지 부탁드립니다~!
> [Feat] search page PM feedback reflected

- src/apis/authApi.js
- src/apis/instance/apiClient.js
- src/pages/login/Login.jsx
- src/pages/login/Login.styles.jsx
아마 안될거같긴한데 테스트 부탁드려요! 세부적으로 조건문좀 건들여봤습니다!
만약 이번에도 안되면 조건으로 거르는 문제라기보다 단순히 요청이 왜 안보내지는지 요청,응답 과정을 위주로 더 살펴보려고합니다.
>
> [Fix] 재발급 api 수정 2트 성공기원

- src/apis/authApi.js
- src/apis/instance/apiClient.js
- src/pages/login/Login.jsx
- src/pages/login/Login.styles.jsx
> [Fix] 액세스토큰 재발급 api 수정 및 정상작동 완료

- src/apis/authApi.js
- src/apis/instance/apiClient.js
> [fix] 리프레쉬 토큰 만료 로그아웃

- src/apis/deleteRoom.js
- src/components/HamburgerMenu/HamburgerMenu2.jsx
- src/components/Reply/Reply.styles.jsx
- src/components/RoomBody/PageRecord.jsx
- src/components/RoomBody/PageRecord.styles.jsx
- src/components/RoomBody/RoomBody.jsx
- src/components/RoomHeader/RoomHeader.jsx
- src/pages/Info/RoomInfo.jsx
- src/pages/Preview/PreviewBody.jsx
- src/pages/Test.jsx
- src/routers/Router.jsx
> [Fix] PageRecord 전체페이지 추가

- src/pages/search/RoomItem.jsx
> [Feat] member status construction fixed

- src/apis/authApi.js
- src/apis/deleteRecordApi.js
- src/apis/instance/apiClient.js
- src/apis/logoutApi.js
- src/apis/popularApi.js
- src/apis/profileApi.js
- src/apis/progressApi.js
- src/apis/recruitRoomApi.js
- src/apis/verification.js
- src/pages/bookmark/Bookmark.jsx
- src/pages/category/Category.jsx
- src/pages/home/Home.jsx
- src/pages/login/Login.jsx
- src/pages/onboarding/Onboarding.jsx
- src/pages/record/Record.jsx
> [fix] 콘솔로그 삭제

- src/pages/signup/PasswordInput.jsx
> 로그인, 회원가입 비밀번호 눈아이콘 기존과 반대로 반전
>
> [Fix] 눈알모양 반전

- src/pages/mypage/accountInfo/Account.jsx
> [fix] 비밀번호 placeholder 텍스트 수정
